classdef network < handle

properties

    %%% replicate count
    Nreplicates = 1;

    %%% Flags
    flags = struct(...
        'isave',                true, ...
        'iplot',                true, ...
        'ilog',                 true, ...
        'savemode',             true, ...
        'imanualseed',          false, ...
        'idefect',              false, ...
        'ipotential',           true, ...
        'idumpsettings',        false, ...
        'iversbose_settings',   false ...
    );

    %%% Domain
    domain = struct(...
        'b',                                1.6, ...
        'dimension',                        2, ...
        'Lx',                               150, ...
        'Ly',                               150, ...
        'Lz',                               10, ...
        'scale',                            1, ...
        'boundary',                         'fixed', ...
        'seed',                             12345, ...
        'write_location',                   '../examples/output', ...
        'lammps_data_file',                 'PolyNetwork', ...
        'lammps_viz_file',                  'PolyVisual', ...
        'bond_table_file',                  'bond', ...
        'smp_number',                       1, ...
        'xlo',                              [], ...
        'xhi',                              [], ...
        'ylo',                              [], ...
        'yhi',                              [], ...
        'zlo',                              [], ...
        'zhi',                              [], ...
        'Max_atom',                         [], ...
        'Max_bond',                         [], ...
        'node_scatter_max_tries',           [], ...
        'bond_global_try_limit',            [], ...
        'max_attempts_without_progress',    [], ...
        'max_tries_per_node_sample',        [], ...
        'min_node_sep',                     [], ...
        'min_node_sep2',                    [] ...
    );

    %%% Architecture subclass
    architecture = [];

    %%% Per/atom
    peratom = struct(...
        'Max_peratom_bond',[], ...
        'min_degree_keep',2 ...
    );

    %%% Per/bond subclass
    perbond = [];

    %%% Defect
    defect = struct(...
        'density_mode',         'area_frac', ...
        'n_voids',              0, ...
        'void_area_frac',       0.75, ...
        'size_dist',            'gaussian', ...
        'radius_mean',          12, ...
        'radius_std',           4, ...
        'radius_min',           2, ...
        'radius_max',           30, ...
        'shape_roughness',      0.3, ...
        'shape_n_modes',        2, ...
        'void_overlap',         false, ...
        'bridge_width',         1, ...
        'center_distribution', 'clustered', ...
        'n_cluster_parents',    2, ...
        'cluster_spread',       10, ...
        'margin_frac',          0.15, ...
        'prune_isolated',       true, ...
        'sparse_network',       true, ...
        'wall_thickness',       18, ...
        'clamp_thickness',      0.12, ...
        'thinning',             false, ...
        'thinning_radius',      0, ...
        'thinning_target_frac', 0.4, ...
        'thinning_min_keep',    0.1, ...
        'bridging',             false, ...
        'bridge_max_dist',      0, ...
        'bridge_void_thresh',   0.25, ...
        'bridge_perp_width',    0, ...
        'bridge_max_degree',    0, ...
        'bridge_max_bonds',     0, ...
        'bridge_min_spacing',   0 ...
    );

    %%% Potential
    pot = struct(...
        'k_LD',                 0.414, ...
        'N_rho',                100000, ...
        'rho_min',              0.0, ...
        'rho_max',              500 ...
    );

    %%% networklog helper class
    log = [];

end

methods

    function obj = network()
        warning off backtrace
        obj.architecture = architecture();
        obj.perbond = bondstyle();
        obj.log = networklog();
    end

    function [obj] = generateNetwork(obj)

        for ii = 1:obj.Nreplicates

            % ---------------------------------------------------------
            % 1. Prepare replicate-specific information
            % ---------------------------------------------------------
            localPrepareReplicate(obj, ii, obj.Nreplicates);

            obj.log.setReplicate(ii);

            % ---------------------------------------------------------
            % 2. Construct domain
            % ---------------------------------------------------------
            SetupDomain(obj);
            syncKuhnAssignmentFromTopology(obj);

            % ---------------------------------------------------------
            % 3. Add atoms   (Atoms has molID at col 2 from every path)
            % ---------------------------------------------------------
            [Atoms, LatticeData] = AddAtoms(obj);

            % ---------------------------------------------------------
            % 4. Add bonds   (all Bonds(:,5) = 0 at this point)
            % ---------------------------------------------------------
            [Atoms, Bonds] = AddBonds(obj, Atoms, LatticeData);
            syncKuhnAssignmentFromTopology(obj);

            % ---------------------------------------------------------
            % 5. Add heterogeneities  (voids + hex-only disorders)
            %    Nvec not yet assigned; pass []. Downstream routines
            %    already gate on ~isempty(Nvec).
            % ---------------------------------------------------------
            Nvec = [];
            [Atoms, Bonds, Nvec] = AddHeterogeneities(obj, Atoms, Bonds, Nvec);

            % ---------------------------------------------------------
            % 6. Clean up network  (drops disconnected fragments, etc.)
            % ---------------------------------------------------------
            [Atoms, Bonds, Nvec] = CleanupNetwork(obj, Atoms, Bonds, Nvec);

            % ---------------------------------------------------------
            % 7. Assign exported atom/bond types
            %    Writes Bonds(:,5) directly; returns TypeData for atom
            %    types and bookkeeping. Safe default Bonds(:,5) = 1 when
            %    typing is disabled.
            % ---------------------------------------------------------
            [Bonds, TypeData] = AssignMultiType(obj, Atoms, Bonds);

            % ---------------------------------------------------------
            % 8. Assign per-bond Kuhn segments (type-agnostic)
            % ---------------------------------------------------------
            Nvec = AssignPerBond(obj, Bonds, Atoms);

            % ---------------------------------------------------------
            % 9. Construct local density potential
            % ---------------------------------------------------------
            LDpot = ConstructLDPotential(obj, Atoms, Bonds, Nvec);

            % ---------------------------------------------------------
            % 10. Scale domain if needed
            % ---------------------------------------------------------
            [Atoms, Bonds] = ScaleDomain(obj, Atoms, Bonds);

            % ---------------------------------------------------------
            % 11. Show visualization and statistics
            % ---------------------------------------------------------
            VisualizeNetwork(obj, Atoms, Bonds, Nvec);

            % ---------------------------------------------------------
            % 12. Computes
            % ---------------------------------------------------------
            order = ComputeOrder(obj, Atoms, Bonds);

            % ---------------------------------------------------------
            % 13. Write data files
            % ---------------------------------------------------------
            WriteDataFiles(obj, Atoms, Bonds, Nvec, LDpot, TypeData);

            % ---------------------------------------------------------
            % 14. Write and clear logs
            % ---------------------------------------------------------
            outdir = obj.domain.write_location;
            obj.log.recordNetworkStats(Atoms, Bonds, Nvec, obj, LDpot, order);

            obj.log.writeLogs( fullfile(outdir, obj.log.console_log_file), ...
                   fullfile(outdir, obj.log.network_log_file), obj );
            obj.log.clear();
        end

    end


end
end
