#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=64
#SBATCH --time=12:00:00
#SBATCH --partition=amilan
#SBATCH --qos=normal
#SBATCH --output=sample-%j.out

module purge

module load gcc
module load openmpi
module load fftw

echo "== This is the scripting step! =="
mpirun -np 64 /projects/saas6184/Fracture_polydisp/lammps/build/lmp -in /projects/saas6184/Fracture_polydisp/lammps/
echo "== End of Job ==":
