clc; clear; close all;
warning off backtrace;

%% --------------------- Global Settings ------------------------

% Write directory
write_location = './sweep';

% Simulation settings 
% Network type: 'mono' or 'polydisperse' or 'bimodal' 
dist_type = 'bimodal';

% Simulation type: 'unnotched' or 'notched'
sim_type = 'unnotched';

% HPC settings
iHPC = true;               % true: also write job submission scripts
HPC_type = 'Dane';         % 'Dane' or 'Milan'

% Location to [.dat, .log, .table] files
% Note: directory must include all files generated by NetworkGen (using auto save_name_mode)
data_location = 'C:\Users\zwhit\GitClones\MesoNetwork\NetworkGen\networks';

% location to template files 
temp_location = './InputScripts/Templates';
batch_location = './InputScripts/Batch';

% Simulation options
clampFrac = 0.05;        % Fraction of sample height to clamp in simulations

%% --------------------- Store the options ----------------------
options.dist_type = dist_type;
options.sim_type = sim_type;
options.iHPC = iHPC;
options.HPC_type = HPC_type;
options.data_location = data_location;
options.write_location = write_location;
options.clampFrac = clampFrac;
%% --------------------- Run the Builder ------------------------

% parse directory contents
[Data] = ParseDirectory(data_location);

if Data.Nlogs > 0
    fprintf('Found %d log files in %s\n', Data.Nlogs, data_location);

    if Data.Ndats == 0
        error('No .dat files found in %s', data_location);
    end
    if Data.Ntabs == 0
        error('No .table files found in %s', data_location);
    end
    if Data.Ndats == Data.Nlogs 
    elseif Data.Ndats == 2*Data.Nlogs
        warning('Found 2 .dat files for every .log... ignoring visual.dat')
    else
        error('Mismatch in number of .dat and .log files in %s', data_location);
    end
    if Data.Ndats ~= 2*Data.Nlogs
    end
    if Data.Ntabs ~= 2*Data.Nlogs
        error('Mismatch in number of .table and .log files in %s', data_location);
    end
else
    error('no log files found in %s', data_location);
end

% parse logs
[logs] = ParseLogs(data_location,Data);

% error checks - check that type in log matches dist_type
for iLog = 1:Data.Nlogs
    if strcmpi(dist_type,'bimodal') 
        if ~strcmpi(logs(iLog).sample_type,'BD')
            error('Log file %s sample type (%s) does not match dist_type (%s)', ...
            Data.logs{iLog}, logs(iLog).sample_type, dist_type);
        end
    elseif strcmpi(dist_type,'polydisperse')
        if ~strcmpi(logs(iLog).sample_type,'PD')
            error('Log file %s sample type (%s) does not match dist_type (%s)', ...
            Data.logs{iLog}, logs(iLog).sample_type, dist_type);
        end
    elseif strcmpi(dist_type,'monodisperse')
        if ~strcmpi(logs(iLog).sample_type,'MD')
            error('Log file %s sample type (%s) does not match dist_type (%s)', ...
            Data.logs{iLog}, logs(iLog).sample_type, dist_type);
        end
    else
        error('Unknown Log file %s sample type (%s)',Data.logs{iLog}, logs(iLog).sample_type)
    end
end

% get the correct template input file
writeInputs(Data,logs,options)

% Finish
fprintf('Finished building runs.\n');
